### ISSUE TITLE
Should Operadics be in `Cartfile.private`?

### ISSUE THREAD

**Issue by griotspeak** [typelift/Swiftx#21]
`Operadics` seems necessary to build `Swiftx` but is not pulled down by `carthage update` when I depend on `Swiftx` from a mac project. If I `cd` into `/Carthage/Checkouts/Swiftx` and then run `carthage bootstrap`, I can then get the mac app to run `carthage update` successfully but codesign fails.

Failure aside, it looks as though `Cartfile.private` should be used for dependencies that aren't necessarily useful in release but that doesn't look like a fitting description of `Operadics`

**Comment by CodaFi** [comment]
Methinks what happened is I didn't `--use-submodules` for Operadics the first time around.  That should resolve your problem and stuff for anyone else who doesn't want to use Carthage.

**Comment by CodaFi** [comment]
I've resolved this in #20.  Let me know if that fixes anything.

**Comment by griotspeak** [comment]
That changed some things. Now I get 

```
A shell task failed with exit code 65:
** BUILD FAILED **
The following build commands failed:
CompileSwift normal x86_64     ~/Development/ChordalText/Carthage/Checkouts/Swiftx/SwiftxTests/SectionSpec.swift
CompileSwift normal x86_64     ~/Development/ChordalText/Carthage/Checkouts/Swiftx/SwiftxTests/EitherSpec.swift
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)`
```

in the log:
`~/Development/ChordalText/Carthage/Checkouts/Swiftx/SwiftxTests/SectionSpec.swift:11:8: error: no such module 'SwiftCheck'
import SwiftCheck`

**Comment by CodaFi** [comment]
Well, shit.  This is why I need build tools backing my commits :disappointed:.  Testing bundle didn't have SwiftCheck copied along with everything else.  That part is fixed by #23, or at least `--no-skip-current` doesn't bork.

**Comment by CodaFi** [comment]
So this doesn't happen again, can you checkout #23 just to make sure I have everything in place?

**Comment by griotspeak** [comment]
I think that you missed adding the `SwiftCheck.xcodeproj` to `Swiftx.xcodeproj`

**Comment by CodaFi** [comment]
It's under Supporting Files.

**Comment by CodaFi** [comment]
Wipe out your Carthage directory. It won't checkout the submodules otherwise.

**Comment by griotspeak** [comment]
My apologies. It checked it out just fine before as well. Xcode simply expects it in the wrong place. 
Expected at  `~/Development/ChordalText/Carthage/Checkouts/SwiftCheck/SwiftCheck.xcodeproj`
when it is actually at `~/Development/ChordalText/Carthage/Checkouts/Swiftx/Carthage/Checkouts/SwiftCheck`

<img width="251" alt="screen shot 2015-07-19 at 9 05 46 am" src="https://cloud.githubusercontent.com/assets/566892/8765980/6415d600-2df5-11e5-846d-663f40722c36.png">

**Comment by griotspeak** [comment]
Is this a carthage setup issue or some other thing? Seems like it is set up with a relative path from the top instead of from `swiftx`. 

EDIT: Yes. The path should be based on the `PROJECT_DIR`, I think.

**Comment by CodaFi** [comment]
So the lesson here is: never trust Xcode to do the right thing the first time around.  I've committed a fix (hopefully) in that branch.

**Comment by griotspeak** [comment]
It builds :+1: Thanks for the help!

**Comment by CodaFi** [comment]
Then it is merged.  Fuck all.
